### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by TimoReusch** [Sidd27/sv-bootstrap-dropdown#7]
I'm using the package with SvelteKit and installed it as a Dev-Dependency. When refreshing a page with a dropdown on it, I get this error:
```
Cannot read properties of undefined (reading 'remove')
TypeError: Cannot read properties of undefined (reading 'remove')
    at Dropdown.svelte:204:18
    at run (/node_modules/svelte/internal/index.mjs:18:12)
    at Array.forEach (<anonymous>)
    at run_all (/node_modules/svelte/internal/index.mjs:24:9)
    at Object.render (/node_modules/svelte/internal/index.mjs:1780:13)
    at render_response (/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:122:27)
    at async render_page (/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:276:10)
    at async resolve (/node_modules/@sveltejs/kit/src/runtime/server/index.js:232:17)
    at async respond (/node_modules/@sveltejs/kit/src/runtime/server/index.js:284:20)
    at async /node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:406:22
```

**Comment by TimoReusch** [comment]
Ok, seems like the bug can be avoided by importing the module like this:
```html
<script>
    import { onMount } from "svelte";

    let Dropdown;

    onMount(async () => {
        Dropdown = (await import("sv-bootstrap-dropdown")).default;
    });

    let dropdownTrigger;
</script>

<svelte:component this={Dropdown} triggerElement={dropdownTrigger}>
    <button
            type="button"
            class="btn btn-secondary"
            bind:this={dropdownTrigger}
    >
        Dropdown
    </button>
    <div slot="DropdownMenu">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <a class="dropdown-item" href="#">Something else here</a>
    </div>
</svelte:component>

```
